name: Update tree

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git identity
        run: |
          git config --global user.name "dothq-robot"
          git config --global user.email "72629236+dothq-robot@users.noreply.github.com"

      - name: Run update script
        run: wget https://raw.githubusercontent.com/dothq/gecko-release/${{ github.sha }}/update.py && python3 update.py